[package]
authors = ["Jerel Unruh <mail@unruhdesigns.com>"]
description = "Membrane is an opinionated crate that generates a Dart package from a Rust library. Extremely fast performance with strict typing and zero copy returns over the FFI boundary via bincode."
edition = "2018"
license = "Apache-2.0"
name = "membrane"
repository = "https://github.com/jerel/membrane"
version = "0.1.0"

[lib]
crate-type = ["lib"]

[features]
generate = ["membrane_macro/generate"]
skip-generate = ["membrane_macro/skip-generate"]

[dependencies]
allo-isolate = "0.1.9"
bincode = {version = "1.3"}
ffi_helpers = "0.2"
futures = "0.3"
heck = "0.3"
inventory = "0.1"
membrane_macro = {version = "0.1", path = "../membrane_macro"}
membrane_types = {version = "0.1", path = "../membrane_types"}
regex = "1.5"
serde = {version = "1.0", features = ["derive"]}
serde-generate = {git = "https://github.com/jerel/serde-reflection", rev = "bd3c78d"}
serde-reflection = {git = "https://github.com/jerel/serde-reflection", rev = "bd3c78d"}

[dev-dependencies]
once_cell = "1.8"
tempfile = "3.2"
tokio = {version = "1", features = ["full"]}
