[package]
authors = ["Jerel Unruh <mail@unruhdesigns.com>"]
edition = "2018"
name = "membrane"
version = "0.1.0"

[lib]
crate-type = ["lib"]

[features]
generate = ["membrane_macro/generate"]

[dependencies]
allo-isolate = "0.1.9"
bincode = {version = "1.3"}
ffi_helpers = "0.2"
futures = "0.3"
heck = "0.3"
inventory = "0.1"
membrane_macro = {path = "../membrane_macro"}
regex = "1.5"
serde = {version = "1.0", features = ["derive"]}
serde-generate = {git = "https://github.com/jerel/serde-reflection", rev = "d3cc7eb"}
serde-reflection = {git = "https://github.com/jerel/serde-reflection", rev = "d3cc7eb"}
