[package]
authors = ["Jerel Unruh <mail@unruhdesigns.com>"]
edition = "2018"
name = "membrane_macro"
version = "0.1.0"

[lib]
proc-macro = true

[features]
generate = []
skip-generate = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
membrane_types = {path = "../membrane_types"}
