name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1

    - name: Rust build
      run: cargo build --verbose
    - name: Rust tests
      run: cargo test --verbose
    - name: Rust generate Dart
      working-directory: ./example
      run: cargo run
    - name: Install llvm
      run: sudo apt-get install -y llvm-dev
    - name: Dart run
      working-directory: ./dart_example
      run: |
        cp ../example/target/debug/libexample.so .
        dart run
